package com.marklogic.gradle.template

class XdbcServerTemplate {

    // The timestamp is updated when the server is added to a package
    final static String TEMPLATE = '''<package-xdbc-server xmlns:cts="http://marklogic.com/cts" xmlns="http://marklogic.com/manage/package/servers">
  <metadata xmlns:srv="http://marklogic.com/manage/package/servers">
    <package-version>2.0</package-version>
    <user>AUTOREPLACED</user>
    <group>AUTOREPLACED</group>
    <host>AUTOREPLACED</host>
    <timestamp>2014-03-18T15:25:16.49-04:00</timestamp>
    <platform>AUTOREPLACED</platform>
  </metadata>
  <config>
    <server-type>xdbc-server</server-type>
    <group-name>%%GROUP_NAME%%</group-name>
    <name>%%SERVER_NAME%%</name>
    <package-xdbc-properties>
      <root>/</root>
      <enabled>true</enabled>
      <port>%%PORT%%</port>
      <display-last-login>false</display-last-login>
      <address>0.0.0.0</address>
      <backlog>256</backlog>
      <threads>32</threads>
      <request-timeout>30</request-timeout>
      <keep-alive-timeout>5</keep-alive-timeout>
      <session-timeout>3600</session-timeout>
      <max-time-limit>3600</max-time-limit>
      <default-time-limit>600</default-time-limit>
      <multi-version-concurrency-control>contemporaneous</multi-version-concurrency-control>
      <distribute-timestamps>fast</distribute-timestamps>
      <authentication>digest</authentication>
      <internal-security>true</internal-security>
      <concurrent-request-limit>0</concurrent-request-limit>
      <log-errors>true</log-errors>
      <debug-allow>true</debug-allow>
      <profile-allow>true</profile-allow>
      <output-sgml-character-entities>none</output-sgml-character-entities>
      <output-encoding>UTF-8</output-encoding>
      <output-method>default</output-method>
      <output-byte-order-mark>default</output-byte-order-mark>
      <output-cdata-section-namespace-uri/>
      <output-cdata-section-localname/>
      <output-doctype-public/>
      <output-doctype-system/>
      <output-escape-uri-attributes>default</output-escape-uri-attributes>
      <output-include-content-type>default</output-include-content-type>
      <output-indent>default</output-indent>
      <output-indent-untyped>default</output-indent-untyped>
      <output-media-type/>
      <output-normalization-form>none</output-normalization-form>
      <output-omit-xml-declaration>default</output-omit-xml-declaration>
      <output-standalone>omit</output-standalone>
      <output-undeclare-prefixes>default</output-undeclare-prefixes>
      <output-version/>
      <output-include-default-attributes>default</output-include-default-attributes>
      <default-xquery-version>1.0-ml</default-xquery-version>
      <pre-commit-trigger-depth>1000</pre-commit-trigger-depth>
      <pre-commit-trigger-limit>10000</pre-commit-trigger-limit>
      <schemas/>
      <namespaces/>
      <request-blackouts/>
      <collation>http://marklogic.com/collation/codepoint</collation>
      <ssl-certificate-template>0</ssl-certificate-template>
      <ssl-allow-sslv3>true</ssl-allow-sslv3>
      <ssl-allow-tls>true</ssl-allow-tls>
      <ssl-hostname/>
      <ssl-ciphers>ALL:!LOW:@STRENGTH</ssl-ciphers>
      <ssl-require-client-certificate>true</ssl-require-client-certificate>
      <ssl-client-certificate-authorities/>
    </package-xdbc-properties>
    <links>
      <group-name>%%GROUP_NAME%%</group-name>
      <database>%%DATABASE_NAME%%</database>
      <modules-database>%%MODULES_DATABASE_NAME%%</modules-database>
    </links>
  </config>
</package-xdbc-server>'''
}
