/*
 * Copyright (c) 2023 MarkLogic Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.marklogic.appdeployer.export;

import com.fasterxml.jackson.databind.JsonNode;
import com.marklogic.appdeployer.command.databases.DeployOtherDatabasesCommand;
import com.marklogic.appdeployer.command.triggers.DeployTriggersCommand;
import com.marklogic.mgmt.selector.PrefixResourceSelector;
import com.marklogic.mgmt.selector.PropertiesResourceSelector;
import com.marklogic.mgmt.selector.RegexResourceSelector;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.Properties;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class ExportTriggersTest extends AbstractExportTest {

	@AfterEach
	public void teardown() {
		undeploySampleApp();
	}

	@Test
	public void test() throws Exception {
		initializeAppDeployer(new DeployOtherDatabasesCommand(1), new DeployTriggersCommand());
		appDeployer.deploy(appConfig);

		Properties props = new Properties();
		props.setProperty("triggers", "my-trigger");

		ExportedResources resources = new Exporter(manageClient)
			.withTriggersDatabase(appConfig.getTriggersDatabaseName())
			.select(new RegexResourceSelector("my-trigger"))
			.export(exportDir);
		verifyExportedResources(resources);

		initializeExportDir();
		resources = new Exporter(manageClient)
			.withTriggersDatabase(appConfig.getTriggersDatabaseName())
			.select(new PrefixResourceSelector("my-trig"))
			.export(exportDir);
		verifyExportedResources(resources);

		initializeExportDir();
		resources = new Exporter(manageClient)
			.withTriggersDatabase(appConfig.getTriggersDatabaseName())
			.select(new PropertiesResourceSelector(props))
			.export(exportDir);
		verifyExportedResources(resources);
	}

	private void verifyExportedResources(ExportedResources resources) throws Exception {
		assertEquals(1, resources.getMessages().size());
		assertEquals(resources.getMessages().get(0),
			"Each exported trigger has the 'id' field removed from it, as that field should be generated by MarkLogic.");

		assertEquals(1, resources.getFiles().size());

		File triggerFile = new File(exportDir, "triggers/my-trigger.json");
		JsonNode json = objectMapper.readTree(triggerFile);
		assertNull(json.get("id"));
		assertEquals("my-trigger", json.get("name").asText());
	}
}
