/*
 * Copyright (c) 2015-2026 Progress Software Corporation and/or its subsidiaries or affiliates. All Rights Reserved.
 */
package com.progress.pdc.client.impl;

import com.google.gson.*;
import com.google.gson.internal.Streams;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.Map;

/**
 * Generated by Copilot - accounts for any issues in the OpenAPI spec where a field's name is not the same as the
 * actual field returned by the API when doing a case-sensitive check. Basically a hack around case-sensitive name bugs
 * in the spec.
 */
public class CaseInsensitiveTypeAdapterFactory implements TypeAdapterFactory {

    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
        TypeAdapter<T> delegate = gson.getDelegateAdapter(this, type);
        return new TypeAdapter<T>() {
            @Override
            public void write(JsonWriter out, T value) throws IOException {
                delegate.write(out, value);
            }

            @Override
            public T read(JsonReader in) {
                JsonElement jsonElement = Streams.parse(in);
                if (jsonElement.isJsonObject()) {
                    jsonElement = makeCaseInsensitive(jsonElement.getAsJsonObject(), type.getRawType());
                }
                return delegate.fromJsonTree(jsonElement);
            }
        };
    }

    private JsonObject makeCaseInsensitive(JsonObject jsonObject, Class<?> clazz) {
        Map<String, String> fieldMap = new HashMap<>();
        for (Field field : clazz.getDeclaredFields()) {
            fieldMap.put(field.getName().toLowerCase(), field.getName());
        }

        JsonObject result = new JsonObject();
        for (Map.Entry<String, JsonElement> entry : jsonObject.entrySet()) {
            String correctName = fieldMap.get(entry.getKey().toLowerCase());
            result.add(correctName != null ? correctName : entry.getKey(), entry.getValue());
        }
        return result;
    }
}
