name: PR Workflow

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read

jobs:
  jira-pr-check:
    name: 🏷️ Validate JIRA ticket ID
    uses: marklogic/pr-workflows/.github/workflows/jira-id-check.yml@main
    with:
      pr-title: ${{ github.event.pull_request.title }}
  copyright-validation:
    name: © Validate Copyright Headers
    uses: marklogic/pr-workflows/.github/workflows/copyright-check.yml@main
    permissions:
      contents: read
      pull-requests: write
      issues: write
